#+title: lsp-server.el
#+author: Naoya Yamashita
#+date: 2020-03-20

[[https://github.com/conao3/lsp-server.el][https://raw.githubusercontent.com/conao3/files/master/blob/headers/png/lsp-server.el.png]]

[[https://github.com/conao3/lsp-server.el/blob/master/LICENSE][https://img.shields.io/github/license/conao3/lsp-server.el.svg?style=flat-square]]
[[https://github.com/conao3/lsp-server.el/releases][https://img.shields.io/github/tag/conao3/lsp-server.el.svg?style=flat-square]]
[[https://github.com/conao3/lsp-server.el/actions][https://github.com/conao3/lsp-server.el/workflows/Main%20workflow/badge.svg]]

An asynchronous Language Server Protocol (LSP) server implementation for Emacs Lisp.

* Overview

lsp-server.el provides an LSP server framework written in Emacs Lisp, enabling you to build language servers that integrate seamlessly with LSP-compatible editors and tools.

** Requirements

- Emacs 26.1 or later

* Installation

** Using leaf.el

#+begin_src emacs-lisp
(leaf lsp-server :ensure t)
#+end_src

** Using package.el

#+begin_src emacs-lisp
(package-install 'lsp-server)
#+end_src

** Manual Installation

Clone this repository and add it to your load path:

#+begin_src emacs-lisp
(add-to-list 'load-path "/path/to/lsp-server.el")
(require 'lsp-server)
#+end_src

* Usage

/Documentation coming soon./

* Contributing

Contributions are welcome. Please feel free to submit issues and pull requests.

** Development Setup

Install [[https://github.com/cask/cask][Cask]] for dependency management:

#+begin_src shell
# macOS
brew install cask

# Manual installation
git clone https://github.com/cask/cask ~/.cask
export PATH="$HOME/.cask/bin:$PATH"
#+end_src

** Development Workflow

#+begin_src shell
# Set up git hooks
make

# Create and switch to a feature branch
git checkout -b feature-name

# Make your changes and run tests
make test

# Commit your changes
git commit -am "Add feature description"

# Push and create a pull request
git push origin feature-name
#+end_src

* License

This project is licensed under the GNU General Public License v3.0. See the [[https://github.com/conao3/lsp-server.el/blob/master/LICENSE][LICENSE]] file for details.

Copyright (c) Naoya Yamashita

* Author

Naoya Yamashita ([[https://github.com/conao3][conao3]])
